# Generated by Django 5.2.16 on 2026-08-08 05:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('duration_minutes', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Theatre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Theatres',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Showtime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starts_at', models.DateTimeField()),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='showtimes', to='catalog.movie')),
                ('theatre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='showtimes', to='catalog.theatre')),
            ],
            options={
                'ordering': ['starts_at'],
            },
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=16)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('HELD', 'Held'), ('BOOKED', 'Booked')], default='AVAILABLE', max_length=16)),
                ('showtime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='catalog.showtime')),
            ],
            options={
                'ordering': ['showtime', 'label'],
                'indexes': [models.Index(fields=['showtime', 'status'], name='catalog_sea_showtim_2fcf02_idx')],
                'constraints': [models.UniqueConstraint(fields=('showtime', 'label'), name='uniq_seat_per_showtime')],
            },
        ),
        migrations.AddIndex(
            model_name='showtime',
            index=models.Index(fields=['movie', 'starts_at'], name='catalog_sho_movie_i_4f0433_idx'),
        ),
        migrations.AddIndex(
            model_name='showtime',
            index=models.Index(fields=['theatre', 'starts_at'], name='catalog_sho_theatre_3ebb7f_idx'),
        ),
    ]
