# Generated by Django 5.2.16 on 2026-08-08 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='idempotency_key',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='OtpDeliveryEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=128, unique=True)),
                ('booking_ref', models.CharField(blank=True, default='', max_length=64)),
                ('ref', models.CharField(blank=True, default='', max_length=64)),
                ('code', models.CharField(blank=True, default='', max_length=32)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('raw_payload', models.JSONField()),
            ],
            options={
                'ordering': ['-received_at'],
                'indexes': [models.Index(fields=['booking_ref', 'received_at'], name='payments_ot_booking_9c308f_idx')],
            },
        ),
    ]
