# Generated by Django 5.2.16 on 2026-08-08 05:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_ref', models.CharField(max_length=64, unique=True)),
                ('phone', models.CharField(max_length=32)),
                ('status', models.CharField(choices=[('HELD', 'Held'), ('PAID', 'Paid'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled')], default='HELD', max_length=16)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'expires_at'], name='booking_boo_status_9e1025_idx'), models.Index(fields=['phone'], name='booking_boo_phone_3c8430_idx')],
            },
        ),
        migrations.CreateModel(
            name='OtpVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(max_length=64, unique=True)),
                ('status', models.CharField(choices=[('SENT', 'Sent'), ('VERIFIED', 'Verified'), ('EXPIRED', 'Expired')], default='SENT', max_length=16)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='otp', to='booking.booking')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='BookingSeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_seats', to='booking.booking')),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='booking_seats', to='catalog.seat')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('seat',), name='uniq_seat_in_booking'), models.UniqueConstraint(fields=('booking', 'seat'), name='uniq_booking_seat')],
            },
        ),
    ]
