# Generated by Django 5.2.16 on 2026-08-08 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='otpverification',
            name='last_delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='otpverification',
            name='last_delivered_code',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
